# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_dgpd <- function(x, xi, sigma, u) {
    .Call('_extrememix_c_dgpd', PACKAGE = 'extrememix', x, xi, sigma, u)
}

c_pgpd <- function(q, xi, sigma, u) {
    .Call('_extrememix_c_pgpd', PACKAGE = 'extrememix', q, xi, sigma, u)
}

c_qgpd <- function(p, xi, sigma, u) {
    .Call('_extrememix_c_qgpd', PACKAGE = 'extrememix', p, xi, sigma, u)
}

c_rgpd <- function(xi, sigma, u) {
    .Call('_extrememix_c_rgpd', PACKAGE = 'extrememix', xi, sigma, u)
}

c_dgamma <- function(x, mu, eta) {
    .Call('_extrememix_c_dgamma', PACKAGE = 'extrememix', x, mu, eta)
}

c_pgamma <- function(q, mu, eta) {
    .Call('_extrememix_c_pgamma', PACKAGE = 'extrememix', q, mu, eta)
}

c_qgamma <- function(p, mu, eta) {
    .Call('_extrememix_c_qgamma', PACKAGE = 'extrememix', p, mu, eta)
}

c_rgamma <- function(mu, eta) {
    .Call('_extrememix_c_rgamma', PACKAGE = 'extrememix', mu, eta)
}

c_dmgamma <- function(x, mu, eta, w) {
    .Call('_extrememix_c_dmgamma', PACKAGE = 'extrememix', x, mu, eta, w)
}

c_pmgamma <- function(q, mu, eta, w) {
    .Call('_extrememix_c_pmgamma', PACKAGE = 'extrememix', q, mu, eta, w)
}

c_qmgamma <- function(p, mu, eta, w) {
    .Call('_extrememix_c_qmgamma', PACKAGE = 'extrememix', p, mu, eta, w)
}

